baseURL = "https://lilyportfolio.netlify.app"
languageCode = "en-us"
title = "Lily's portfolio"
theme = "mediumish-gohugo-theme"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
summaryLength = 25
copyright = "Xue (Lily) Yang - All rights reserved 2021"
enableEmoji = true
publishDir = "docs"
canonifyurls = true
#disqusShortname = "your-shortname-here"
#googleAnalytics = "UA-1XXXXXXX1-1"

[params]
  description ="Learning about Data everyday~"
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  name = "Xue (Lily) Yang"
  thumbnail = "/images/author.png"
  description = "Data Science/Analytics student"

[params.index]
  picture = "/images/profile/profile_1.jpg"
  title = "Xue (Lily) Yang"
  subtitle = ""
  mdtext = '''
Learning everyday about my new passion: Data Science!
### Feel free to explore my projects!
'''
  alertbar = false

[params.social]
  github = "lilyportfolio"
  linkedin = "lily-y-39507787"
  twitter = "<username>"

## Main Menu
[[menu.main]]
    name = "Projects"
    weight = 100
    identifier = "projects"
    url = "/project"
[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 200
    url = "/static/about"
[[menu.main]]
    name = "Contact Me"
    identifier = "contacts"
    weight = 200
    url = "/static/contacts"