[build]
command = "hugo"
publish = "docs"
[build.environment]
HUGO_VERSION = "0.84.4"

[context]
[context.branch-deploy]
command = "hugo -F -b $DEPLOY_PRIME_URL"
[context.deploy-preview]
[context.deploy-preview.environment]
HUGO_VERSION = "0.84.4"
command = "hugo -F -b $DEPLOY_PRIME_URL"
[context.production]
[context.production.environment]
HUGO_VERSION = "0.84.4"
HUGO_ENV = "production"